BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Tag" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Text"	TEXT NOT NULL CHECK(length("Text") > 0) UNIQUE COLLATE NOCASE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DocumentsTags" (
	"DocumentID"	INTEGER NOT NULL,
	"TagID"	INTEGER NOT NULL,
	FOREIGN KEY("TagID") REFERENCES "Tag"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("DocumentID") REFERENCES "Document"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("DocumentID","TagID")
);
CREATE TABLE IF NOT EXISTS "Category" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Title"	TEXT NOT NULL DEFAULT 'Category' CHECK(length("Title") > 0) COLLATE NOCASE,
	"Parent"	INTEGER DEFAULT NULL,
	FOREIGN KEY("Parent") REFERENCES "Category"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE("Parent","Title"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Section" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Title"	TEXT NOT NULL DEFAULT 'Title' CHECK(length("Title") > 0) COLLATE NOCASE,
	"Content"	TEXT NOT NULL DEFAULT '',
	"FirstSubsection"	INTEGER UNIQUE,
	"NextSection"	INTEGER UNIQUE,
	FOREIGN KEY("FirstSubsection") REFERENCES "Section"("ID") ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("NextSection") REFERENCES "Section"("ID") ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Document" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Title"	TEXT NOT NULL DEFAULT 'Document' CHECK(length("Title") > 0) COLLATE NOCASE,
	"Content"	TEXT NOT NULL DEFAULT '',
	"Parent"	INTEGER,
	"FirstSection"	INTEGER UNIQUE,
	FOREIGN KEY("FirstSection") REFERENCES "Section"("ID") ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("Parent") REFERENCES "Category"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE("Parent","Title"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
