BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Tag" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Text"	TEXT NOT NULL CHECK(length("Text") > 0) UNIQUE COLLATE NOCASE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Category" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Title"	TEXT NOT NULL DEFAULT 'Category' CHECK(length("Title") > 0) COLLATE NOCASE,
	"Parent"	INTEGER DEFAULT NULL CHECK("Parent" != "ID"),
	UNIQUE("Parent","Title"),
	FOREIGN KEY("Parent") REFERENCES "Category"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Document" (
	"CategoryID"	INTEGER,
	"SectionID"	INTEGER NOT NULL UNIQUE,
	FOREIGN KEY("SectionID") REFERENCES "Section"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("CategoryID") REFERENCES "Category"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("SectionID")
);
CREATE TABLE IF NOT EXISTS "Section" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Title"	TEXT NOT NULL DEFAULT 'Title' CHECK(length("Title") > 0) COLLATE NOCASE,
	"Content"	TEXT NOT NULL DEFAULT '',
	"Parent"	INTEGER CHECK("ID" != "Parent"),
	"OrderIndex"	INTEGER NOT NULL DEFAULT 0,
	UNIQUE("Parent","Title"),
	UNIQUE("Parent","OrderIndex"),
	FOREIGN KEY("Parent") REFERENCES "Section"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DocumentsTags" (
	"DocumentID"	INTEGER NOT NULL,
	"TagID"	INTEGER NOT NULL,
	UNIQUE("DocumentID","TagID"),
	FOREIGN KEY("TagID") REFERENCES "Tag"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("DocumentID") REFERENCES "Document"("SectionID") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("DocumentID","TagID")
);
CREATE TRIGGER propagate_document_deletion AFTER DELETE ON Document
BEGIN
	DELETE FROM Section WHERE Section.ID=OLD.SectionID;
END;
CREATE TRIGGER tags_cleaner AFTER DELETE ON DocumentsTags
WHEN NOT EXISTS (SELECT * FROM DocumentsTags WHERE TagID=OLD.TagID)
BEGIN
	DELETE FROM Tag WHERE ID=OLD.TagID;
END;
COMMIT;
