//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMOrganizerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMOrganizerApp.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book &apos;{0}&apos; was created successfully..
        /// </summary>
        internal static string BookCreated {
            get {
                return ResourceManager.GetString("BookCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &apos;{0}&apos; was created successfully..
        /// </summary>
        internal static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been deleted..
        /// </summary>
        internal static string DeletedItem {
            get {
                return ResourceManager.GetString("DeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; was created successfully..
        /// </summary>
        internal static string DocumentCreated {
            get {
                return ResourceManager.GetString("DocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already is another item named &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateItemName {
            get {
                return ResourceManager.GetString("DuplicateItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already is a tag &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateTag {
            get {
                return ResourceManager.GetString("DuplicateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a name for the new book:.
        /// </summary>
        internal static string InputBookName {
            get {
                return ResourceManager.GetString("InputBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a name for the new category:.
        /// </summary>
        internal static string InputCategoryName {
            get {
                return ResourceManager.GetString("InputCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a name for the new document:.
        /// </summary>
        internal static string InputDocumentName {
            get {
                return ResourceManager.GetString("InputDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a new name for this item:.
        /// </summary>
        internal static string InputNewName {
            get {
                return ResourceManager.GetString("InputNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a new tag:.
        /// </summary>
        internal static string InputTag {
            get {
                return ResourceManager.GetString("InputTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s name has been changed to &apos;{0}&apos;..
        /// </summary>
        internal static string RenamedSuccessfully {
            get {
                return ResourceManager.GetString("RenamedSuccessfully", resourceCulture);
            }
        }
    }
}
